version: '3.8'

services:
  cabin-server:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8180:8180"
    environment:
      - JAVA_OPTS=-Xmx512m
    command: ["java", "-jar", "tomcat-benchmark-1.0-SNAPSHOT.jar"]
    volumes:
      - gradle-cache:/root/.gradle

volumes:
  gradle-cache: